### ISSUE TITLE
Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by Asgator** [AgentME/webstorage-polyfill#1]
> Error:  Attempted to assign to readonly property.

```
localStorage@webpack:///./~/webstorage-polyfill/index.js 100:0  
 setData(data);
 }
 };
 return obj;
 }

 var localStorage = new Storage('local');
 var sessionStorage = new Storage('session');
 window.localStorage = localStorage; <--- Error here
 window.sessionStorage = sessionStorage;
 })();
 }
 })();
```

Users:
Mobile Safari 10.0
Safari 10.0
Chrome Mobile iOS 53.0.2785

**Comment by Macil** [comment]
Thanks for the report! Yeah, I can reproduce this. Looks like maybe Safari 9 made `window.localStorage` read-only and leaves us no way to replace it with our replacement. I'm going to push an update to make this module not even attempt to for that case.

**Comment by Macil** [comment]
Oh, the original gist that this code was based on was in non-strict mode. It overwrote the `__proto__` property to work in Safari. I'll do that.

**Comment by Asgator** [comment]
@AgentME good, thx!

**Comment by Saidbek** [comment]
I'm getting `TypeError: Assignment to read-only properties is not allowed in strict mode
`, using IE11 with disabled DOM storage

@AgentME  any ideas?
